import {
  Eye,
  EyeOff,
  Mail,
  Lock,
  User,
  KeyRound,
  ShieldCheck,
  ArrowRight,
  Dumbbell,
  CheckCircle2,
  Package,
  ShoppingBag,
  TrendingUp,
  ShieldHalf,
  Search,
  Plus,
  Trash2,
  Filter,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  X,
  Loader2,
  ImagePlus,
  ChevronsLeft,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  Activity,
  Calendar,
  ArrowUpRight,
  ArrowDownRight,
  Box,
  ShoppingCart,
  Clock,
  Check,
  XCircle,
  LayoutDashboard,
  Users,
  BarChart3,
  Settings,
  LogOut,
  Menu,
  Bell,
  ChevronDown,
  UserPlus,
  Shield,
  MoreHorizontal,
  Phone,
  ChevronUp,
  Truck,
  IndianRupee,
  ReceiptText,
  Pencil,
  MapPin,
} from 'lucide-react';

export const ADMIN_ICONS = {
  EYE: Eye,
  EYEOFF: EyeOff,
  MAIL: Mail,
  LOCK: Lock,
  USER: User,
  KEYROUND: KeyRound,
  SHIELDCHECK: ShieldCheck,
  ARROWRIGHT: ArrowRight,
  DUMBBELL: Dumbbell,
  CHECKCIRCLE2: CheckCircle2,
  SHOPPINGCART: ShoppingCart,
  SHOPPINGBAG: ShoppingBag,

  //admin products page icons
  PACKAGE: Package,
  PRODUCTS: Box,
  TRENDINGUP: TrendingUp,
  SHIELDHALF: ShieldHalf,
  SEARCH: Search,
  PLUS: Plus,
  TRASH2: Trash2,
  EDIT: Pencil,
  EYE: Eye,
  FILTER: Filter,
  ARROWUPDOWN: ArrowUpDown,
  ARROWUP: ArrowUp,
  ARROWDOWN: ArrowDown,
  X: X,
  LOADER2: Loader2,
  IMAGEPLUS: ImagePlus,
  CHEVRONSLEFT: ChevronsLeft,
  CHEVRONLEFT: ChevronLeft,
  CHEVRONDOWN: ChevronDown,
  CHEVRONRIGHT: ChevronRight,
  CHEVRONS_RIGHT: ChevronsRight,

  //admin dashboard icons
  ACTIVITY: Activity,
  CALENDAR: Calendar,
  ARROWUPRIGHT: ArrowUpRight,
  ARROWDOWNRIGHT: ArrowDownRight,
  LAYOUTDASHBOARD: LayoutDashboard,
  USERS: Users,
  SETTING: Settings,
  BARCHART: BarChart3,
  LOGOUT: LogOut,
  MENU: Menu,
  BELL: Bell,

  //admin orders page icons
  CLOCK: Clock,
  CHECK: Check,
  XCIRCLE: XCircle,
  TRUCK: Truck,
  INDIANRUPEE: IndianRupee,
  RECEIPTTEXT: ReceiptText,
  MAP: MapPin,

  //admin users page icons
  USERPLUS: UserPlus,
  SHIELD: Shield,
  MOREHORIZONTAL: MoreHorizontal,
  PHONE: Phone,
  CHEVRONUP: ChevronUp,
};
