import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline';
import {
  ArrowLeft,
  BadgePercent,
  Eye,
  Heart,
  Minus,
  Phone,
  Plus,
  ShoppingCart,
  Shuffle,
  Star,
  Trash2,
  Truck,
  CalendarDays,
  Clock,
  Mail,
  FileText,
  MessageSquare,
  CalendarCheck,
  UserRound,
  Dumbbell,
  Timer,
  ClipboardList,
  Package,
  CheckCircle2,
  XCircle,
  ChevronDown,
  ChevronUp,
  ShoppingBag,
  ArrowRight,
  ReceiptText,
} from 'lucide-react';

export const PAGE_ICONS = {
  // General
  ARROWLEFT: ArrowLeft,
  OFFER: BadgePercent,
  TRUCK: Truck,
  PHONE: Phone,
  TRASH: Trash2,
  CART: ShoppingCart,
  BAR: Bars3Icon,
  SHUFFLE: Shuffle,
  EYE: Eye,
  STAR: Star,
  HEART: Heart,
  MINUS: Minus,
  PLUS: Plus,
  XMARK: XMarkIcon,

  // Appointment
  CALENDAR: CalendarDays,
  CALENDAR_CHECK: CalendarCheck,
  CLOCK: Clock,
  MAIL: Mail,
  FILE_TEXT: FileText,
  MESSAGE: MessageSquare,
  USER: UserRound,
  DUMBBELL: Dumbbell,
  TIMER: Timer,
  CLIPBOARD: ClipboardList,

  //orders
  PACKAGE: Package,
  CHECKCIRCLE: CheckCircle2,
  XCIRCLE: XCircle,
  CHEVRONDOWN: ChevronDown,
  CHEVRONUP: ChevronUp,
  SHOPPINGBAG: ShoppingBag,
  TRUCK: Truck,
  ARROWRIGHT: ArrowRight,
  CALENDARDAYS: CalendarDays,
  RECEIPTTEXT: ReceiptText,
};
