import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline';
import {
  ArrowLeft,
  BadgePercent,
  Eye,
  Heart,
  Minus,
  Phone,
  Plus,
  ShoppingCart,
  Shuffle,
  Star,
  Trash2,
  Truck,
  CalendarDays,
  Clock,
  Mail,
  FileText,
  MessageSquare,
  CalendarCheck,
  UserRound,
  Dumbbell,
  Timer,
  ClipboardList,
  Package,
  CheckCircle2,
  XCircle,
  ChevronDown,
  ChevronUp,
  ShoppingBag,
  ArrowRight,
  ReceiptText,
  Loader2,
  LogOut,
  Image,
  Layers,
  Archive,
  DollarSign,
  Tag,
  Home,
  Scissors,
  Share2,
  Banknote,
  CreditCard,
  Wallet,
  ChevronRight,
  MapPin,
  Shield,
  Gift,
  Tags,
  MessageSquarePlus,
  UserCircle,
  MessageCircle,
  Building2,
  Pencil,
  ChevronDownIcon,
  X,
  Motorbike,
} from 'lucide-react';

export const PAGE_ICONS = {
  // General
  ARROWLEFT: ArrowLeft,
  OFFER: BadgePercent,
  TRUCK: Truck,
  PHONE: Phone,
  TRASH: Trash2,
  CART: ShoppingCart,
  BAR: Bars3Icon,
  SHUFFLE: Shuffle,
  EYE: Eye,
  STAR: Star,
  HEART: Heart,
  MINUS: Minus,
  PLUS: Plus,
  XMARK: XMarkIcon,
  LOADER: Loader2,
  LOGOUT: LogOut,
  HOME: Home,
  PENCIL: Pencil,
  X: X,

  // Appointment
  CALENDAR: CalendarDays,
  CALENDAR_CHECK: CalendarCheck,
  CLOCK: Clock,
  MAIL: Mail,
  FILE_TEXT: FileText,
  MESSAGE: MessageSquare,
  MESSAGEADD: MessageSquarePlus,
  USER: UserRound,
  DUMBBELL: Dumbbell,
  TIMER: Timer,
  CLIPBOARD: ClipboardList,

  //orders
  PACKAGE: Package,
  CHECKCIRCLE: CheckCircle2,
  XCIRCLE: XCircle,
  CHEVRONDOWN: ChevronDown,
  CHEVRONUP: ChevronUp,
  SHOPPINGBAG: ShoppingBag,
  TRUCK: Truck,
  ARROWRIGHT: ArrowRight,
  CALENDARDAYS: CalendarDays,
  RECEIPTTEXT: ReceiptText,
  MOTORBIKE: Motorbike,

  //PRODUCTS PAGE
  SCISSORS: Scissors,
  SHARE2: Share2,

  //EXTRA
  TAG: Tag,
  TAGS: Tags,
  DOLLARSIGN: DollarSign,
  ARCHIVE: Archive,
  LAYERS: Layers,
  IMAGE: Image,
  USERCIRCLE: UserCircle,
  MESSAGECIRCLE: MessageCircle,
  BUILDING: Building2,

  //checkout page icons
  BANKNOTE: Banknote,
  CREDITCARD: CreditCard,
  WALLET: Wallet,
  CHEVRONRIGHT: ChevronRight,
  MAPPIN: MapPin,
  SHIELD: Shield,
  GIFT: Gift,

  //shadcn ui icons
  CHEVRONDOWNICON: ChevronDownIcon,
};
